version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase..
      - aws --version
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on 'date'
      - git clone https://github.com/debmanas/servicecatalog.git
      - ls -larth
      - git --version
      - git clone https://github.com/debmanas/codebuildproject.git
      - touch file.txt
      - cd codebuildproject>>file.txt
      - cat file.txt
      - ls -lrth
      - for p in $(cat file.txt);
        do
        aws s3api put-object --bucket codepipeline-us-east-2-858035149410 --key foldername/p --body p;
        done
      - aws s3 ls
     
  post_build:
    commands:
      - echo Build completed on  time 'date' 
      - aws servicecatalog create-portfolio-share --portfolio-id port-t3mictubnuptg --account-id 649664284872
      