version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase..
      - aws --version
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on 'date'
      - git clone https://github.com/debmanas/servicecatalog.git
      - ls -larth
      - git --version
      - git clone https://github.com/debmanas/codebuildproject.git
      - touch file.txt
      - cd codebuildproject
      - #for dir in /codebuildproject/*/;
        #do
        #dir=${dir%*/};
        #echo "${dir##*/}";
        #done
      - #cat file.txt
      - zip codebuildproject.zip *
      - ls -l
      - aws s3 cp codebuildproject.zip  s3://rest-apps1  
      - #find . -maxdepth 1 -mindepth 1 -type f -printf '%f\n'
      - #ls -lrth
      - #for p in $(cat file.txt);
        #do
        #aws s3 cp   --bucket codepipeline-us-east-2-858035149410 --key foldername/p --body p;
        #done
      - aws s3 ls
     
  post_build:
    commands:
      - echo Build completed on  time 'date' 
      - aws servicecatalog create-portfolio-share --portfolio-id port-t3mictubnuptg --account-id 649664284872
      