version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase..
      - aws --version
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on 'date'
      - git clone https://github.com/debmanas/servicecatalog.git
      - ls -larth
      - git --version
      - git clone https://github.com/debmanas/codebuildproject.git
      - touch file.txt
      - cd codebuildproject
      - #for dir in /codebuildproject/*/;
        #do
        #dir=${dir%*/};
        #echo "${dir##*/}";
        #done
      - #cat file.txt
      - zip codebuildproject.zip *
      - ls -l
      - aws s3 cp codebuildproject.zip  s3://rest-apps1  
      - #find . -maxdepth 1 -mindepth 1 -type f -printf '%f\n'
      - #ls -lrth
      - #for p in $(cat file.txt);
        #do
        #aws s3 cp   --bucket codepipeline-us-east-2-858035149410 --key foldername/p --body p;
        #done
      - aws s3 ls
      - ACC=$(aws sts get-caller-identity --query 'Account' | tr -d '"')
      - echo $ACC
      - childAcc=""
      - childAccComma=${childAcc// /,}
      - allACC="$ACC $childAcc"
      - echo $childAcc
     
  post_build:
    commands:
      - echo Build completed on  time 'date' 
      - aws sts assume-role --role-arn arn:aws:iam::649664284872:role/AWSCloudFormationStackSetExecutionRole --role-session-name deployer --query 'Credentials.[AccessKeyId,SecureAccessKey,SessionToken]' --output text >/tmp/credentials
      - AWS_ACCESS_KEY_ID=`cat /tmp/credentials |awk '{print $1}'`
      - AWS_SECRET_ACCESS_KEY= `cat /tmp/credentials |awk '{print $2}'`
      - AWS_SESSION_TOKEN= `cat /tmp/credentials |awk '{print $3}'`
      - aws sts get-caller_identity
      -aws cloudformation create-stack --stack-name myteststack --template-body file://stack.yml
      - aws servicecatalog create-portfolio-share --portfolio-id port-t3mictubnuptg --account-id 649664284872
      